CREATE SCHEMA ATL
GO

CREATE TABLE ATL.pessoa(
	Nome	VARCHAR(30) NOT NULL,
	CC		INT	PRIMARY KEY NOT NULL CHECK ( CC > 0 AND CC < 999999999),
	Morada	VARCHAR(35),
	Nascimento	DATE NOT NULL
);

CREATE TABLE ATL.encarregado(
	Email		VARCHAR(25),
	Contacto	INT NOT NULL,
	CC			INT PRIMARY KEY NOT NULL REFERENCES ATL.pessoa(CC)
);

CREATE TABLE ATL.aluno(
	CC			INT PRIMARY KEY NOT NULL REFERENCES ATL.pessoa(CC),
	Autorizado	CHAR(3) NOT NULL,
	Relacao		VARCHAR(30) NOT NULL
);


CREATE TABLE ATL.professor(
	CC		INT PRIMARY KEY NOT NULL REFERENCES ATL.pessoa(CC),
	N_funcionario INT NOT NULL CHECK(N_funcionario > 0),
	Email		VARCHAR(25),
	Contacto	INT
);

CREATE TABLE ATL.turma(
	ID			INT PRIMARY KEY NOT NULL CHECK(ID > 0),
	Ano_letivo	CHAR(9),
	Designacao	VARCHAR(5) NOT NULL,
	N_alunos	INT NOT NULL,
	CC			INT REFERENCES ATL.professor(CC)
);

CREATE TABLE ATL.atividade(
	ID		INT PRIMARY KEY NOT NULL CHECK(ID > 0),
	Designacao VARCHAR(20) NOT NULL,
	Custo	FLOAT NOT NULL
);

CREATE TABLE ATL.tem(
	ID_turma		INT   REFERENCES ATL.turma(ID) NOT NULL,
	ID_atividade	INT  REFERENCES ATL.atividade(ID)  NOT NULL,
	PRIMARY KEY(ID_turma, ID_atividade)
);

CREATE TABLE ATL.frequenta(
	ID			INT  REFERENCES ATL.atividade(ID)  NOT NULL,
	CC			INT  REFERENCES ATL.aluno(CC)  NOT NULL,
	Tem_turma	CHAR(3)	NOT NULL,
	PRIMARY KEY(ID,CC)
);